[package]
name = "broken_links"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.2"
reqwest = "0.11.6"
tokio = { version = "1.13.0", features = ["full"] }
error-chain = "0.12.4"